#!/usr/bin/env python3
import os
import sys
import subprocess

import common

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)

sys.path.insert(0, os.path.join(REPO_ROOT, "pythonlib"))
import buildlib

def main():
    bin_dir = os.path.join(common.SRC_PATH, "bin")
    buildlib.makedirs(bin_dir)
    ninja_bin = os.path.join(bin_dir, "ninja")
    if not os.path.exists(ninja_bin):
        os.rename(os.path.join(common.SRC_PATH, "ninja"), ninja_bin)
    tar_path = os.path.join(SCRIPT_DIR, "ninja-" + common.VERSION + ".tar")
    buildlib.run(["tar", "-C", common.SRC_PATH, "-cvf", tar_path, "bin/ninja"])
    buildlib.run(["xz", "-f", tar_path])

main()
