#!/usr/bin/env python3
import os
import sys
import shutil
import subprocess

import common

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)

sys.path.insert(0, os.path.join(REPO_ROOT, "pythonlib"))
import buildlib

def main():
    buildlib.rmtree(common.SRC_PATH)
    buildlib.run(["git", "clone", "https://github.com/endrazine/wcc.git", common.SRC_PATH,
                  "-b", "v" + common.VERSION], cwd=SCRIPT_DIR)
    buildlib.run(["git", "submodule", "update", "--init", "--recursive"], cwd=common.SRC_PATH)
    # TODO: this currently fails because we need libbfd
    buildlib.run(["make", "-C", os.path.join(common.SRC_PATH, "src", "wcc")])

main()
