#!/usr/bin/env python3
import os
import sys
import common

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)

sys.path.insert(0, os.path.join(REPO_ROOT, "pythonlib"))
import buildlib

ARCHIVE_BASENAME = f"{common.VERSION}.tar.gz"
SRC_URL = f"https://github.com/sigurd-dev/mkblob/archive/{ARCHIVE_BASENAME}"

def main():
    archive_path = buildlib.download(SRC_URL, ARCHIVE_BASENAME)

    buildlib.rmtree(common.SRC_PATH)
    buildlib.run(["tar", "-C", SCRIPT_DIR, "-xf", archive_path])

    buildlib.run(["bash", "makeall_el8.sh"], cwd=common.SRC_PATH)

main()
