#!/usr/bin/env python3
import os
import sys
import subprocess

import common

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)

sys.path.insert(0, os.path.join(REPO_ROOT, "pythonlib"))
import buildlib

def main():
    tar_path = os.path.join(SCRIPT_DIR, "python-" + common.VERSION + ".tar")
    buildlib.run(["tar", "-C", common.OUT_DIR, "-cvf", tar_path, "."])
    print("create-pkg: compressing...(this can take a while)")
    buildlib.run(["xz", "-f", tar_path])

main()
